//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LO_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public int CabinetId { get; set; }
        public int Quanlity { get; set; }
        public int ProviderId { get; set; }
        public Nullable<int> Price { get; set; }
        public System.DateTime InputDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Item Item { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
    }
}
