//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LO_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransPermissionList
    {
        public string Username { get; set; }
        public string PermissionType { get; set; }
        public string Cabinet_Type { get; set; }
        public string Note { get; set; }
        public int PermissionId { get; set; }
        public int UserId { get; set; }
        public int CabinetTypeId { get; set; }
    }
}
