//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LO_Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionsId { get; set; }
        public int ItemId { get; set; }
        public int Quanlity { get; set; }
        public int ProviderCabinetId { get; set; }
        public int ReceiverCabinetId { get; set; }
        public System.DateTime InputDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> Price { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Cabinet Cabinet1 { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
